apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
spec:
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-api-feed
    spec:
      containers:
      - name: udagram-api-feed
        image: callspadeoz123/udagram-api-feed:v1
        resources:
          limits:
            memory: "1500Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
          - name: URL
            valueFrom:
              configMapKeyRef:
                name: udagram-configmap
                key: URL
          - name: POSTGRES_USERNAME
            valueFrom: 
              secretKeyRef:
                name: udagram-api-feed-secret
                key: POSTGRES_USERNAME
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: udagram-api-feed-secret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: udagram-api-feed-secret
                key: POSTGRES_DB
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: udagram-configmap
                key: POSTGRES_HOST
          - name: AWS_BUCKET
            valueFrom:
              configMapKeyRef:
                name: udagram-configmap
                key: AWS_BUCKET
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                name: udagram-configmap
                key: AWS_REGION
          - name: aws_access_key_id
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: AWS_ACCESS_KEY_ID
          - name: aws_secret_key
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: AWS_SECRET_KEY
          - name: AWS_PROFILE
            valueFrom:
              configMapKeyRef:
                name: udagram-configmap
                key: AWS_PROFILE
          - name: JWT_SECRET
            valueFrom:
              configMapKeyRef:
                name: udagram-configmap
                key: JWT_SECRET