- docker build -t udagram-api-feed ./udagram-api-feed
- docker build -t udagram-api-user ./udagram-api-user
- docker build -t udagram-frontend ./udagram-frontend
- docker build -t reverseproxy ./udagram-reverseproxy


- docker tag udagram-api-feed callspadeoz123/udagram-api-feed:v1
- docker tag udagram-api-user callspadeoz123/udagram-api-user:v1
- docker tag udagram-frontend callspadeoz123/udagram-frontend:v1
- docker tag reverseproxy callspadeoz123/reverseproxy:v1

- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push callspadeoz123/udagram-api-feed:v1
- docker push callspadeoz123/udagram-frontend:v1
- docker push callspadeoz123/udagram-api-user:v1
- docker push callspadeoz123/reverseproxy:v1
