language: node_js
node_js: 
  - 12

services:
  - docker

install: 
 - echo "Nothing needs to be installed"

before_script:
  - echo "No tests"

script:
  - echo "Building docker images..."

  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy

  - echo "Images built successfully"
  - echo "Tagging images..."

  - docker tag udagram-api-feed callspadeoz123/udagram-api-feed:v1
  - docker tag udagram-api-user callspadeoz123/udagram-api-user:v1
  - docker tag udagram-frontend callspadeoz123/udagram-frontend:v1
  - docker tag reverseproxy callspadeoz123/reverseproxy:v1

  - echo "Images tagged successfully"

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push callspadeoz123/udagram-api-feed:v1
  - docker push callspadeoz123/udagram-frontend:v1
  - docker push callspadeoz123/udagram-api-user:v1
  - docker push callspadeoz123/reverseproxy:v1

  - echo "Images pushed successfully"
