apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-user
spec:
  selector:
    matchLabels:
      app: udagram-api-user
  template:
    metadata:
      labels:
        app: udagram-api-user
    spec:
      containers:
      - name: udagram-api-user
        image: callspadeoz123/udagram-api-user:v1
        resources:
          limits:
            memory: "1500Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
          - name: URL
            valueFrom:
              configMapKeyRef:
                name: udagram-configmap
                key: URL
          - name: JWT_SECRET
            valueFrom:
              configMapKeyRef:
                name: udagram-configmap
                key: JWT_SECRET
          - name: POSTGRES_USERNAME
            valueFrom: 
              secretKeyRef:
                name: udagram-api-user-secret
                key: POSTGRES_USERNAME
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: udagram-api-user-secret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: udagram-api-user-secret
                key: POSTGRES_DB
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: udagram-configmap
                key: POSTGRES_HOST
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                name: udagram-configmap
                key: AWS_REGION
          - name: AWS_BUCKET
            valueFrom:
              configMapKeyRef:
                name: udagram-configmap
                key: AWS_BUCKET
          - name: AWS_PROFILE
            valueFrom:
              configMapKeyRef:
                name: udagram-configmap
                key: AWS_PROFILE