apiVersion: v1
kind: ConfigMap
metadata:
  name: udagram-configmap
data:
  POSTGRES_HOST: udagramdev.cd068vqifbes.us-east-1.rds.amazonaws.com
  AWS_BUCKET: mscv-prod-bucket
  AWS_REGION: us-east-1
  AWS_PROFILE: default
  JWT_SECRET: testing
  URL: http://localhost:8100